fitur_1/urls.py
from django.conf.urls import url
from .views import index, add_status


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

fitur_2/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
    url(r'^$', index, name='index'),

]

fitur_3/urls.py
from django.conf.urls import url
from .views import index, add_friend
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
]

fitur_4/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name = 'index'),
]

project1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur_1.urls as fitur_1
import fitur_3.urls as fitur_3
import fitur_2.urls as fitur_2
import fitur_4.urls as dashboard
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(fitur_2, namespace='profile')),
    url(r'^add_friend/', include(fitur_3,namespace='add_friend')),
    url(r'^status/', include(fitur_1, namespace= 'fitur-1')),
    url(r'^statistic/', include(dashboard, namespace= 'dashboard')),
    url(r'^$', RedirectView.as_view(url="/status/", permanent="true"), name='index'),
]

fitur_1/models.py
from django.db import models

class Status(models.Model):
    updatestat = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_2/models.py
from django.db import models


class DataProfile(models.Model):
	name = models.CharField(max_length=30)
	birthday = models.CharField(max_length=20)
	gender = models.CharField(max_length=6)
	expertise = models.TextField(max_length=200)
	description = models.CharField(max_length=140)
	email = models.CharField(max_length=30)

fitur_3/models.py
from django.db import models

# Create your models here.
class Friends(models.Model):
    name = models.TextField(max_length=60)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_4/models.py
from django.db import models

# Create your models here.

fitur_1/forms.py
from django import forms

class Status_form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    updatestat_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 3,
        'class': 'todo-form-textarea',
        'placeholder':'Apa yang ada dipikiran anda...'
    }

    updatestat = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=updatestat_attrs))

fitur_3/forms.py
from django import forms


class add_friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    nama_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan nama...'
    }
    url_attrs = {
        'type': 'url',
        'class': 'todo-form-textarea',
        'placeholder':'Masukan url...'
    }

    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=nama_attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=url_attrs))

fitur_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_form
from .models import Status

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Sukma Firdaus" #TODO Implement yourname
    status = Status.objects.all()
    response['status'] = status
    html = 'fitur_1/fitur_1.html'
    response['Status_form'] = Status_form
    return render(request, html, response)

def add_status(request):
    form = Status_form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['updatestat'] = request.POST['updatestat']
        status = Status(updatestat=response['updatestat'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

fitur_2/views.py
from django.shortcuts import render
from .models import DataProfile


response={}

name = 'Grup 7'
birthday = '04 Oktober 2017'
gender = '-'
email = 'grup7@mail.com'
description = "Terdiri dari Taliya, Edwin, Daus, Albert"
expert = ["push", "pull", "clone"]

profil = DataProfile(name = name, birthday = birthday, gender= gender, email = email, description=description, expertise=expert)


def index(request):
	response = {'name' : profil.name, 'birthday' : profil.birthday, 'gender': profil.gender, 'expertise': profil.expertise, 'description' : profil.description, 'email': profil.email}
	html = 'fitur_2/fitur_2.html'
	return render(request, html, response)

fitur_3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from .forms import add_friend_Form
from .models import Friends
# Create your views here.
friend_list = {}
response = {}
def index(request):

    #response['author'] = "" #TODO Implement yourname
    friends = Friends.objects.all()
    response['friends'] = friends
    html = 'fitur_3.html'
    response['add_friend_Form'] = add_friend_Form
    return render(request, html, response)


def add_friend(request):
    form = add_friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friends = Friends(name=response['name'],url=response['url'])
        friends.save()
        return HttpResponseRedirect('/add_friend/')
    else:
        return HttpResponseRedirect('/add_friend/')

fitur_4/views.py
from django.shortcuts import render
from fitur_1.models import Status
from fitur_3.models import Friends

author = 'Albert Christian Bangun'
# Create your views here.

def index(request):
    #feed= Status.objects.all().count()
    #friend =Friends.objects.all().count()
    #post=Status.objects.last().updatestat
    #date=Status.objects.last().created_date
    #response = {'author':author,'feed':feed,'friend':friend,'postan':post,'date':date}
    #return render(request, 'statistic.html', response)

    posts = Status.objects.all().count()
    if posts == 0:
        temp= Status(updatestat = 'Hi')
        temp.save()
        latest_post = Status.objects.last().updatestat

    
    latest_post = Status.objects.last().updatestat
    date = Status.objects.last().created_date
    friend = Friends.objects.all().count()

    response = {'author': author, 'posts': posts, 'date': date, 'latest_post': latest_post, 'friend': friend}
    return render(request, 'statistic.html', response)

fitur_1/templates/fitur_1/fitur_1.html
{% extends "fitur_1/layout/base.html" %}

{% load staticfiles %}
{% block content %}

<head>
    <meta charset="utf-8">
    <title> Beranda </title>
    <link rel = "stylesheet" type = "text/css" link href = "{% static '/css/fitur_1.css' %}"/>
</head>
<div id="isi">
    <section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'fitur-1:add_status' %}">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ Status_form }}
            <div class="button-group pull-right">
                <input id="submit" type="submit" class="btn btn-primary" value="Submit">
            </div>
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if status %}
                {% for data in status reversed %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="photo" id="foto">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShx5bw-WW3ntwdMdJHC0W_nl2eN-2-VVRHL0Rn5qlxpMY80MEw" style="width:50px;height:50px;border:0;" width="70px" class="img-circle">
                                <span id="nama">
                                    Grup 7
                                </span>
                                <div class="to-do-list-description" id="statusorang">
                                    {{data.updatestat|linebreaksbr}}
                                </div>
                                <div class="to-do-list-date-added" id="tanggal">
                                    <i> {{data.created_date}} </i>
                                </div>
                            </div>
                            <hr>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Tidak ada status yang telah di post!</strong>
            </div>
            {% endif %}
        </div>
    </div>
</section>
</div>


{% endblock %} 

fitur_1/templates/fitur_1/form_result.html
    {% extends "lab_4/layout/base.html" %}
    {% block title %} Pesan dari {{ name }} {% endblock %}
    {% block content %}
    <textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}}
        by {{ email }}
    </textarea>
    {% endblock %}
    {% block footer %}
        <p> &copy; {{name}} </p>
    {% endblock %}

fitur_1/templates/fitur_1/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_1.css' %}" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="updatestat" content="STATUS">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Beranda {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_1/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_1/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
        });
    </script>
</body>
</html>

fitur_1/templates/fitur_1/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p id="futer">
	<i>&copy;Kelompok 7 - B
</p>

fitur_1/templates/fitur_1/partials/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>facebook7</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color:lightblue ">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <img src="https://s-media-cache-ak0.pinimg.com/originals/60/fa/e5/60fae561ba736ece444397e4c3b0a805.png" style="width:50px;height:50px;border:0;" width="70px">
          <!-- <a class="navbar-brand" href="#">facebook7</a> -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/status/">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add_friend/">Friends</a>
              </li>
			  <li class="nav-item">
                <a class="nav-link" href="/statistic/">Stats</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
	{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

fitur_1/templates/fitur_1/table.html
{% extends "lab_4/layout/base.html" %}

{% block title %} Kumpulan Pesan {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

fitur_2/templates/fitur_2/fitur_2.html
{% extends "header.html" %}


{% block content %}
<style>
    .button {
    background-color: #cbd1c8;
    border: none;
    color: black;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    cursor: pointer;
    }
    .button1 {border-radius: 12px;}
    .column {
    float: left;
    width: 10%;
    padding: 10px;}
    .column1 {
    float: left;
    width: 50%;
    padding: 10px;}

}
</style>

<section name="profile">
    <div class="container">
        <h2>Profile</h2>
        <center><img src="http://www.fanphobia.net/uploads/actors_2/56079/lucy-beaumont.jpg" style="width: 200px; height: 200px; border-radius: 100%"></center>
        <center>
            <h2> 
                <font face="verdana">{{name}}</font>
            </h2>
        </center>
        <hr/>
        <div class = "column"></div>
        <div class="column"></div>
        <div class="column"></div>
        <div class="column"></div>
        <div class = "column">
        
            <p> Birthday </p>
            <p> Gender </p>
            <p style='padding-top:6px;padding-bottom:6px'> Expertise </p>
            <p> Description </p>
            <p> Email </p>
        </div>
        <div class="column1 ">
            <p> {{birthday}} </p>
            <p> {{gender}} </p>
            <p> {% for ii in expertise %}
                    <button style='vertical-align: middle;' class='button button1'>{{ ii }}</button>
                {% endfor %}
            <p> {{description}} </p>
            <p> {{email}} </p>
        </div>
        <div class="column"></div>
        <div class="column"></div>
        <div class="column"></div>
    </div>
</section>
{% endblock %}
        

fitur_2/templates/fitur_2/footer.html
<p align-"center"><i>&copy Kelompok 7 - B</p>

fitur_2/templates/fitur_2/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>facebook7</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>

<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color:lightblue ">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">facebook7</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/status/">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add_friend/">Friends</a>
              </li>
			  <li class="nav-item">
                <a class="nav-link" href="/statistic/">Stats</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    
	   {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

fitur_2/templates/fitur_2/layout/base.html
{% load staticfiles %}
{% laod static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">  
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_2.css' %}" />

    <title> 
        {% block title %} Profile {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_2/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_2/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur_3/templates/fitur_3.html
{% extends "header.html" %}
{% block content %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <title>Add Friend</title>
  </head>
  <body>
    <div class = "container">
    <section name ="form">
    <h1>Add Friend</h1>
    <form class="" action="add_friend" method="POST">
      {% csrf_token %}
      {{ add_friend_Form }}
      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
    </form>
  </section>
    <h1>List Friend</h1>
    {% if friends %}
    <table class ="table">
      {% for friend in friends %}
        <tr>
          <td>{{friend.name}}</td>
          <td><a href ={{friend.url}}>{{friend.url}}</a></td>
          <td>Added {{friend.created_date}}</td>
        </tr>
      {% endfor %}
    </table>
    {% endif %}
  </div>
  </body>
</html>
{% endblock %}

fitur_3/templates/footer.html
<p align = "center"><i>&copy Kelompok 7 - B</p>

fitur_3/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>facebook7</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color:lightblue ">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">facebook7</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/status/">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add_friend/">Friends</a>
              </li>
			  <li class="nav-item">
                <a class="nav-link" href="/statistic/">Stats</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
	{% endblock %}
</body>
     
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

fitur_4/templates/footer.html
<p align="center"><i> &copy Kelompok 7 - B</p>

fitur_4/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>facebook7</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color:lightblue ">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">facebook7</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/status/">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add_friend/">Friends</a>
              </li>
			  <li class="nav-item">
                <a class="nav-link" href="/statistic/">Stats</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
	{% endblock %}
</body>
        <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "footer.html" %}
        {% endblock %}
    </footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>